### ISSUE TITLE
make planeringsrapport.md

### ISSUE THREAD

**Issue by patrikja** [DSLsofMath/BScProj#1]
Jag ser att planeringsrapporten också är incheckad som .md men jag lyckades inte uppdatera den versionen med make. Vänligen ta bort .md-versionen eller fixa så make fungerar.
Mvh,
  Patrik

patrikj@etyd:~/src/DSLM/BScProj/Dokument/Planeringsrapport$ make planeringsrapport.md
pandoc -s --bibliography=referenser.bib --csl ieee.csl -t markdown_github --reference-links -f latex planeringsrapport.tex -o planeringsrapport.md
pandoc: Error running filter pandoc-citeproc

Error at "input" (line 22, column 14):
unexpected "{"
expecting letter or lf new-line
\HRule \[0.08cm]
             ^
Makefile:9: recipe for target 'planeringsrapport.md' failed
make: **\* [planeringsrapport.md] Error 83
patrikj@etyd:~/src/DSLM/BScProj/Dokument/Planeringsrapport$ pandoc --version
pandoc 1.13.2.1

**Comment by Jassob** [comment]
Fixed as of [b649281](https://github.com/DSLsofMath/BScProj/commit/b649281ba709262ecb11e5a6317ba4c729027611)
